name: Test & publish 📦 to PyPI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Launch integration tests
    uses: girvel/tiny_storage/.github/workflows/test.yml@master
  publish:
    name: Publish 📦 to PyPI
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
