name: Publish 📦 to PyPI as -unstable

on:
  push:
    branches: [master]

jobs:
  main:
    name: Launch workflow
    uses: girvel/python-library-workflow/.github/workflows/main.yaml@master
    with:
      publish_as: 'unstable'
    secrets:
      REPO_TOKEN: ${{ github.token }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
