name: Test 📦

on:
  push:
  workflow_call:

jobs:
  test:
    name: Launch tests
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install coverage

    - name: Launch unit tests
      run: coverage run --source tiny_storage -m unittest discover -s tests
      
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: .coverage.unit-${{ matrix.os }}
        path: .coverage

    - name: Launch integration tests
      run: coverage run --source tiny_storage -m unittest discover -s integration_tests
      
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v2
      with:
        name: .coverage.integration-${{ matrix.os }}
        path: .coverage
        
  generate-badge:
    name: Generate coverage badge
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install coverage
    
    - name: Download coverage artifacts
      uses: actions/download-artifact@v2
    
    - name: Combine coverage files
      run: coverage combine .coverage.*
      
    - name: Calculate coverage
      id: calculate
      run: >
        echo '::set-output name=coverage::'$(
          coverage report 
            | sed -n 's/TOTAL[[:space:]]*[[:digit:]]*[[:space:]]*[[:digit:]]*[[:space:]]*// p'
        )
        
    - name: Generate a badge
      uses: RubbaBoy/BYOB@v1.2.1
      with:
        NAME: coverage
        LABEL: 'Test coverage'
        STATUS: ${{ steps.calculate.outputs.coverage }}
        COLOR: blue 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
