name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Launch unit tests
        run: |
          python -m unittest discover -s tests

      - name: Launch integration tests
        run: |
          python -m unittest discover -s integration_tests
