name: Test 📦

on:
  push:
    branches-ignore:
    - master

jobs:
  test:
    name: Launch tests
    uses: girvel/python-library-workflow/test.yaml@master
    with:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
