name: Test 📦

on:
  push:
    branches-ignore:
    - master

jobs:
  test:
    name: Launch tests
    uses: girvel/python-library-workflow/.github/workflows/test.yaml@master
    with:
      REPO_TOKEN: ${{ github.token }}
